# Generated by Django 4.2.27 on 2026-03-09 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_enabled', models.BooleanField(default=True)),
                ('telegram_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('quiet_start', models.TimeField(blank=True, null=True)),
                ('quiet_end', models.TimeField(blank=True, null=True)),
                ('notify_event_created', models.BooleanField(default=True)),
                ('notify_event_modified', models.BooleanField(default=True)),
                ('notify_event_reminder', models.BooleanField(default=True)),
                ('notify_agent_proposal', models.BooleanField(default=True)),
                ('notify_agent_digest', models.BooleanField(default=True)),
                ('notify_conflict', models.BooleanField(default=True)),
                ('notify_invitation', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to='circles.circlemember')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='MemberPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=100)),
                ('value', models.JSONField()),
                ('confirmed', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('learned', 'Learned'), ('imported', 'Imported')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='circles.circlemember')),
            ],
            options={
                'ordering': ['category', 'key'],
                'indexes': [models.Index(fields=['member', 'category'], name='agents_memb_member__a7f46c_idx')],
                'unique_together': {('member', 'category', 'key')},
            },
        ),
        migrations.CreateModel(
            name='AgentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('event_create', 'Create Event'), ('booking_propose', 'Propose Booking'), ('event_suggest', 'Suggest Event'), ('digest_send', 'Send Digest')], max_length=30)),
                ('payload', models.JSONField()),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('integrity_hash', models.CharField(max_length=64)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_actions', to='circles.circlemember')),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_actions', to='circles.circle')),
            ],
            options={
                'ordering': ['-proposed_at'],
                'indexes': [models.Index(fields=['circle', 'action_type'], name='agents_agen_circle__c5ad0e_idx'), models.Index(fields=['proposed_at'], name='agents_agen_propose_140ae2_idx')],
            },
        ),
    ]
