# Generated by Django 4.2.27 on 2026-03-09 00:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circles', '0001_initial'),
        ('app', '0034_alter_tasksourceconfig_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(default='#2D6A4F', max_length=7)),
                ('icon', models.CharField(default='calendar', max_length=50)),
                ('visibility', models.CharField(choices=[('family', 'Family'), ('adults_only', 'Adults Only'), ('private', 'Private'), ('custom', 'Custom')], default='family', max_length=20)),
                ('caldav_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='circles.circlemember')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=500)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('event_type', models.CharField(choices=[('event', 'Event'), ('recurring', 'Recurring'), ('background', 'Background'), ('task', 'Task'), ('dependent', 'Dependent')], default='event', max_length=20)),
                ('display_mode', models.CharField(default='normal', max_length=20)),
                ('visibility', models.CharField(choices=[('family', 'Family'), ('adults_only', 'Adults Only'), ('private', 'Private'), ('custom', 'Custom')], default='family', max_length=20)),
                ('recurrence_rule', models.TextField(blank=True, null=True)),
                ('dependent_type', models.CharField(blank=True, choices=[('transport', 'Transport'), ('meal', 'Meal'), ('accompany', 'Accompany'), ('break', 'Break')], max_length=20, null=True)),
                ('booking_ref', models.JSONField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('etag', models.CharField(blank=True, default='', max_length=64)),
                ('caldav_raw', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calendars.calendar')),
                ('linked_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='app.localtask')),
                ('members', models.ManyToManyField(blank=True, related_name='events', to='circles.circlemember')),
                ('parent_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='calendars.event')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_events', to='circles.circlemember')),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset_minutes', models.IntegerField()),
                ('channel', models.CharField(choices=[('push', 'Push'), ('telegram', 'Telegram'), ('email', 'Email')], max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='calendars.event')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='circles.circlemember')),
            ],
            options={
                'unique_together': {('event', 'member', 'offset_minutes', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='EventException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_start', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recurring_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='calendars.event')),
                ('replacement_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='calendars.event')),
            ],
            options={
                'unique_together': {('recurring_event', 'original_start')},
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['calendar', 'start_at', 'end_at'], name='calendars_e_calenda_166a11_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['parent_event'], name='calendars_e_parent__46a005_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['linked_task'], name='calendars_e_linked__36498e_idx'),
        ),
    ]
