# Generated by Django 4.2.27 on 2026-03-13 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0001_initial'),
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('ical_url', models.URLField(max_length=1000)),
                ('color', models.CharField(default='#9CA3AF', max_length=7)),
                ('refresh_minutes', models.PositiveIntegerField(default=15)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('last_etag', models.CharField(blank=True, default='', max_length=128)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_calendar_id', models.CharField(help_text="Google Calendar ID (e.g. 'primary' or email address).", max_length=255)),
                ('google_account_email', models.EmailField(help_text='Google account email for gws CLI auth.', max_length=254)),
                ('sync_token', models.CharField(blank=True, default='', max_length=500)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('sync_direction', models.CharField(choices=[('both', 'Bidirectional'), ('push', 'Ase to Google only'), ('pull', 'Google to Ase only')], default='both', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='google_event_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Google Calendar event ID (set when synced from/to Google).', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='ical_uid',
            field=models.CharField(blank=True, default='', help_text='Original UID from external iCal feed (arbitrary string, not a UUID).', max_length=512),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['subscription', 'ical_uid'], name='calendars_e_subscri_f76f24_idx'),
        ),
        migrations.AddField(
            model_name='googlecalendarsync',
            name='ase_calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_syncs', to='calendars.calendar'),
        ),
        migrations.AddField(
            model_name='googlecalendarsync',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_syncs', to='circles.circlemember'),
        ),
        migrations.AddField(
            model_name='calendarsubscription',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='circles.circlemember'),
        ),
        migrations.AddField(
            model_name='event',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imported_events', to='calendars.calendarsubscription'),
        ),
        migrations.AlterUniqueTogether(
            name='googlecalendarsync',
            unique_together={('member', 'google_calendar_id')},
        ),
    ]
