# Generated by Django 4.2.27 on 2026-03-09 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OIDCConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_url', models.URLField(help_text='OIDC discovery endpoint base URL (e.g. https://auth.example.com)', verbose_name='Issuer URL')),
                ('client_id', models.CharField(max_length=255, verbose_name='Client ID')),
                ('client_secret', models.CharField(help_text='Stored encrypted at rest via field-level encryption or Vault.', max_length=500, verbose_name='Client Secret')),
                ('backend_type', models.CharField(choices=[('lldap', 'LLDAP (lightweight)'), ('zitadel', 'Zitadel (premium)')], help_text='Which directory backend to use for user provisioning.', max_length=20, verbose_name='IAM Backend')),
                ('api_url', models.URLField(help_text='Base URL for the IAM management API (LLDAP GraphQL endpoint or Zitadel Management API root).', verbose_name='Management API URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OIDC Configuration',
                'verbose_name_plural': 'OIDC Configurations',
            },
        ),
        migrations.CreateModel(
            name='TrustedExternalIdP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_url', models.URLField(help_text='Must exactly match the ``iss`` claim in incoming JWTs.', unique=True, verbose_name='Issuer URL')),
                ('client_id', models.CharField(max_length=255, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=500, verbose_name='Client Secret')),
                ('display_name', models.CharField(help_text="Shown to the user on the login screen (e.g. 'Acme Corp SSO').", max_length=100, verbose_name='Display Name')),
                ('enabled', models.BooleanField(default=True, help_text='Disabled IdPs are ignored during authentication.', verbose_name='Enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trusted External IdP',
                'verbose_name_plural': 'Trusted External IdPs',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='CircleInviteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Opaque random token included in the invite URL.', max_length=64, unique=True, verbose_name='Invite Token')),
                ('email', models.EmailField(help_text='Pre-fill for display; the OIDC email must match.', max_length=254, verbose_name='Invited Email')),
                ('circle_id', models.PositiveIntegerField(help_text='ID of the Circle the invitee will be added to.', verbose_name='Circle ID')),
                ('role', models.CharField(default='member', max_length=32, verbose_name='Role')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Used At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to=settings.AUTH_USER_MODEL, verbose_name='Invited By')),
            ],
            options={
                'verbose_name': 'Circle Invite Token',
                'verbose_name_plural': 'Circle Invite Tokens',
            },
        ),
        migrations.CreateModel(
            name='AppSpecificPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable label (e.g. 'iPhone de Awa').", max_length=100, verbose_name='Name')),
                ('password_hash', models.CharField(help_text='bcrypt hash of the application-specific password.', max_length=255, verbose_name='Password Hash')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Used At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank for a non-expiring password.', null=True, verbose_name='Expires At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_passwords', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'App-Specific Password',
                'verbose_name_plural': 'App-Specific Passwords',
                'ordering': ['-created_at'],
            },
        ),
    ]
