# Generated by Django 4.2.27 on 2026-03-08 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0030_alter_rewards_ranks"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="auto_mode_selection",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="deep_work_duration",
            field=models.PositiveSmallIntegerField(default=90),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="energy_tracking_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="free_flow_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="mode_label_map",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Mapping of mode → label list for auto-detection",
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="profile_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="sprint_duration",
            field=models.PositiveSmallIntegerField(default=45),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="streak_freeze_days_remaining",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="streak_freeze_reset_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="youtube_default_playlists",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Mode → YouTube playlist URL mapping",
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="theme",
            field=models.CharField(
                choices=[
                    ("default", "default"),
                    ("white", "white"),
                    ("forest", "forest"),
                    ("aquamarine", "aquamarine"),
                    ("garnet", "garnet"),
                    ("coral", "coral"),
                    ("afrofuturist", "afrofuturist"),
                ],
                default="default",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("deep_work", "Deep Work"),
                            ("pomodoro", "Pomodoro"),
                            ("sprint", "Sprint"),
                            ("free_flow", "Free Flow"),
                        ],
                        default="pomodoro",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "planned_duration",
                    models.PositiveIntegerField(
                        help_text="Planned duration in minutes"
                    ),
                ),
                (
                    "actual_duration",
                    models.PositiveIntegerField(
                        blank=True, help_text="Actual duration in minutes", null=True
                    ),
                ),
                ("task_id", models.CharField(blank=True, max_length=255, null=True)),
                ("task_title", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "task_source",
                    models.CharField(
                        default="local",
                        help_text="Adapter source: local, plane, etc.",
                        max_length=64,
                    ),
                ),
                (
                    "energy_before",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                    ),
                ),
                (
                    "energy_after",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                    ),
                ),
                (
                    "playlist_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("completed", models.BooleanField(default=False)),
                (
                    "tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="app.tag",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="LocalTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To Do"),
                            ("in_progress", "In Progress"),
                            ("done", "Done"),
                        ],
                        default="todo",
                        max_length=16,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("urgent", "Urgent"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("labels", models.JSONField(blank=True, default=list)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                (
                    "estimated_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="local_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EnergyReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("session_start", "Session Start"),
                            ("session_end", "Session End"),
                            ("check_in", "Check-in"),
                        ],
                        default="check_in",
                        max_length=16,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="energy_readings",
                        to="app.session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="energy_readings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
