# Generated by Django 4.2.27 on 2026-03-08 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0031_usersettings_auto_mode_selection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='mode',
            field=models.CharField(choices=[('deep_work', 'Deep Work'), ('pomodoro', 'Pomodoro'), ('kids', 'Kids'), ('sprint', 'Sprint'), ('free_flow', 'Free Flow')], default='pomodoro', max_length=16),
        ),
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('daily_plan', 'Daily Plan'), ('task_decomposition', 'Task Decomposition'), ('reflection_prompt', 'Reflection Prompt'), ('energy_suggestion', 'Energy Suggestion')], max_length=32)),
                ('content', models.JSONField(help_text='Structured suggestion data from AI')),
                ('accepted', models.BooleanField(blank=True, help_text='True=accepted, False=dismissed, None=pending user action', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
