# Generated by Django 4.2.27 on 2026-03-08 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0032_add_aisuggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=500)),
                ('source', models.CharField(choices=[('youtube', 'YouTube'), ('spotify', 'Spotify'), ('other', 'Other')], default='youtube', max_length=16)),
                ('mode', models.CharField(blank=True, choices=[('deep_work', 'Deep Work'), ('pomodoro', 'Pomodoro'), ('kids', 'Kids'), ('sprint', 'Sprint'), ('free_flow', 'Free Flow')], default='', help_text='Restrict playlist to a specific focus mode; blank = any mode', max_length=16)),
                ('is_default', models.BooleanField(default=False, help_text='If True this playlist is auto-selected when starting a session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaskSourceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('local', 'Local (Ase)'), ('plane', 'Plane'), ('github', 'GitHub Issues')], help_text='Adapter identifier — must match a key in adapters.registry._REGISTRY', max_length=32)),
                ('enabled', models.BooleanField(default=True, help_text='When False this source is excluded from unified task queries')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Adapter-specific config (api keys, slugs, etc.)')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Order in which sources are shown and queried (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_source_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Source Config',
                'verbose_name_plural': 'Task Source Configs',
                'ordering': ['display_order', 'created_at'],
                'unique_together': {('user', 'source_type')},
            },
        ),
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('planned_tasks', models.JSONField(blank=True, default=list, help_text='List of task objects planned for this day')),
                ('focus_score', models.FloatField(blank=True, help_text='Focus score 0-100, computed at end of day', null=True)),
                ('reflection', models.TextField(blank=True, default='', help_text='End-of-day reflection text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Plan',
                'verbose_name_plural': 'Daily Plans',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('first_session', 'First Session'), ('sessions_10', '10 Sessions'), ('sessions_50', '50 Sessions'), ('sessions_100', '100 Sessions'), ('sessions_500', '500 Sessions'), ('streak_3', '3-Day Streak'), ('streak_7', '7-Day Streak'), ('streak_30', '30-Day Streak'), ('energy_tracker', 'Energy Tracker'), ('deep_work_master', 'Deep Work Master'), ('first_reflection', 'First Reflection'), ('reflections_7', '7 Reflections'), ('first_plan', 'First Daily Plan'), ('plans_30', '30 Daily Plans')], max_length=32)),
                ('unlocked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement_type')},
            },
        ),
    ]
