# Generated by Django 4.2.27 on 2026-03-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_playlist_tasksourceconfig_dailyplan_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksourceconfig',
            name='source_type',
            field=models.CharField(choices=[('local', 'Local (Ase)'), ('plane', 'Plane'), ('github', 'GitHub Issues'), ('superproductivity', 'Super Productivity')], help_text='Adapter identifier — must match a key in adapters.registry._REGISTRY', max_length=32),
        ),
    ]
