# Generated by Django 4.2.27 on 2026-03-09 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('preset', models.CharField(choices=[('family', 'Famille'), ('colocation', 'Colocation'), ('team', 'Equipe'), ('club', 'Club / Association'), ('custom', 'Personnalise')], default='family', max_length=20)),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('agent_enabled', models.BooleanField(default=True)),
                ('agent_budget_limit', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CircleMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('display_name', models.CharField(max_length=100)),
                ('avatar_color', models.CharField(default='#E76F51', max_length=7)),
                ('avatar_emoji', models.CharField(blank=True, default='', max_length=10)),
                ('invite_token', models.CharField(blank=True, default='', max_length=255)),
                ('invite_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('membership_type', models.CharField(choices=[('local', 'Local'), ('federated', 'Federated')], default='local', max_length=20)),
                ('external_issuer', models.URLField(blank=True, null=True)),
                ('external_sub', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='circles.circle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='circle',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('tenant_id',), name='unique_primary_circle_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='circlemember',
            constraint=models.UniqueConstraint(condition=models.Q(('membership_type', 'federated')), fields=('circle', 'external_issuer', 'external_sub'), name='unique_federated_member_per_circle'),
        ),
        migrations.AlterUniqueTogether(
            name='circlemember',
            unique_together={('user', 'circle')},
        ),
    ]
